In [1]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost:  19614.8
Prediction:
 [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]
10 Cost:  14.0682
Prediction:
 [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]
 ...
1990 Cost:  4.9197
Prediction:
 [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]
2000 Cost:  4.89449
Prediction:
 [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]
'''

0 Cost:  62547.29 
Prediction:
 [-75.96345  -78.27629  -83.83015  -90.80436  -56.976482]
10 Cost:  14.468626 
Prediction:
 [145.26407 187.59541 178.152   194.48586 145.81136]
20 Cost:  13.822504 
Prediction:
 [145.9478  188.39003 178.94907 195.3521  146.41212]
30 Cost:  13.749193 
Prediction:
 [145.96422 188.38263 178.95592 195.35777 146.4012 ]
40 Cost:  13.67629 
Prediction:
 [145.97856 188.3728  178.96031 195.36082 146.38844]
50 Cost:  13.603815 
Prediction:
 [145.99286 188.36302 178.9647  195.36386 146.37572]
60 Cost:  13.531695 
Prediction:
 [146.00711 188.35324 178.9691  195.3669  146.36302]
70 Cost:  13.459941 
Prediction:
 [146.02135 188.34352 178.9735  195.36995 146.35036]
80 Cost:  13.388664 
Prediction:
 [146.03552 188.33382 178.97784 195.37292 146.33774]
90 Cost:  13.317709 
Prediction:
 [146.04967 188.32413 178.98221 195.37595 146.32515]
100 Cost:  13.247167 
Prediction:
 [146.06377 188.31447 178.98654 195.37894 146.31259]
110 Cost:  13.176931 
Prediction:
 [146.07785 188.3

970 Cost:  8.365171 
Prediction:
 [147.15631 187.56671 179.32283 195.61014 145.34155]
980 Cost:  8.321417 
Prediction:
 [147.16742 187.55911 179.32626 195.61247 145.33168]
990 Cost:  8.277808 
Prediction:
 [147.17853 187.55151 179.32967 195.6148  145.32182]
1000 Cost:  8.234464 
Prediction:
 [147.1896  187.54395 179.33308 195.61716 145.31201]
1010 Cost:  8.191355 
Prediction:
 [147.20064 187.53638 179.33649 195.61946 145.30222]
1020 Cost:  8.148522 
Prediction:
 [147.21164 187.52887 179.33987 195.6218  145.29245]
1030 Cost:  8.105857 
Prediction:
 [147.22261 187.52133 179.34326 195.6241  145.2827 ]
1040 Cost:  8.063463 
Prediction:
 [147.23357 187.51385 179.34663 195.6264  145.273  ]
1050 Cost:  8.021299 
Prediction:
 [147.24448 187.50638 179.34998 195.6287  145.2633 ]
1060 Cost:  7.979327 
Prediction:
 [147.25537 187.49893 179.35333 195.63098 145.25363]
1070 Cost:  7.937616 
Prediction:
 [147.26624 187.49152 179.35669 195.63327 145.244  ]
1080 Cost:  7.8960905 
Prediction:
 [147.27707

'\n0 Cost:  19614.8\nPrediction:\n [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]\n10 Cost:  14.0682\nPrediction:\n [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]\n ...\n1990 Cost:  4.9197\nPrediction:\n [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]\n2000 Cost:  4.89449\nPrediction:\n [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]\n'

In [2]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost:  7105.46
Prediction:
 [[ 80.82241058]
 [ 92.26364136]
 [ 93.70250702]
 [ 98.09217834]
 [ 72.51759338]]
10 Cost:  5.89726
Prediction:
 [[ 155.35159302]
 [ 181.85691833]
 [ 181.97254944]
 [ 194.21760559]
 [ 140.85707092]]
...
1990 Cost:  3.18588
Prediction:
 [[ 154.36352539]
 [ 182.94833374]
 [ 181.85189819]
 [ 194.35585022]
 [ 142.03240967]]
2000 Cost:  3.1781
Prediction:
 [[ 154.35881042]
 [ 182.95147705]
 [ 181.85035706]
 [ 194.35533142]
 [ 142.036026  ]]
'''

0 Cost:  126121.6 
Prediction:
 [[-159.22546]
 [-197.2163 ]
 [-191.33363]
 [-208.02669]
 [-152.1618 ]]
10 Cost:  13.888784 
Prediction:
 [[154.9044 ]
 [180.36964]
 [180.69513]
 [197.10442]
 [135.84653]]
20 Cost:  12.669057 
Prediction:
 [[155.84157]
 [181.52121]
 [181.81673]
 [198.32693]
 [136.73022]]
30 Cost:  12.604082 
Prediction:
 [[155.83118]
 [181.53384]
 [181.81612]
 [198.32741]
 [136.74518]]
40 Cost:  12.539492 
Prediction:
 [[155.81792]
 [181.54295]
 [181.8121 ]
 [198.32416]
 [136.75745]]
50 Cost:  12.475268 
Prediction:
 [[155.80472]
 [181.55206]
 [181.80812]
 [198.32092]
 [136.76968]]
60 Cost:  12.411341 
Prediction:
 [[155.79152]
 [181.56113]
 [181.80411]
 [198.31767]
 [136.78188]]
70 Cost:  12.347745 
Prediction:
 [[155.77838]
 [181.57019]
 [181.80013]
 [198.31444]
 [136.79405]]
80 Cost:  12.284551 
Prediction:
 [[155.76527]
 [181.57921]
 [181.79616]
 [198.31122]
 [136.80618]]
90 Cost:  12.221666 
Prediction:
 [[155.75218]
 [181.5882 ]
 [181.7922 ]
 [198.308  ]
 [136.81828

960 Cost:  7.86742 
Prediction:
 [[154.74167]
 [182.28401]
 [181.48643]
 [198.05669]
 [137.75685]]
970 Cost:  7.8282957 
Prediction:
 [[154.7314 ]
 [182.29109]
 [181.48332]
 [198.05412]
 [137.76643]]
980 Cost:  7.7893906 
Prediction:
 [[154.72115]
 [182.29813]
 [181.48022]
 [198.05151]
 [137.77597]]
990 Cost:  7.7507033 
Prediction:
 [[154.71094]
 [182.30516]
 [181.47713]
 [198.04895]
 [137.78549]]
1000 Cost:  7.712208 
Prediction:
 [[154.70074]
 [182.3122 ]
 [181.47406]
 [198.04639]
 [137.79498]]
1010 Cost:  7.6739135 
Prediction:
 [[154.6906 ]
 [182.31918]
 [181.471  ]
 [198.04382]
 [137.80447]]
1020 Cost:  7.6358824 
Prediction:
 [[154.68047]
 [182.32616]
 [181.46793]
 [198.04126]
 [137.81389]]
1030 Cost:  7.597991 
Prediction:
 [[154.67036]
 [182.33313]
 [181.46489]
 [198.03871]
 [137.82332]]
1040 Cost:  7.5603056 
Prediction:
 [[154.66028]
 [182.34007]
 [181.46184]
 [198.03618]
 [137.83272]]
1050 Cost:  7.5228453 
Prediction:
 [[154.65025]
 [182.347  ]
 [181.45882]
 [198.03365]
 [

1870 Cost:  5.045623 
Prediction:
 [[153.91377]
 [182.85468]
 [181.23671]
 [197.84526]
 [138.53175]]
1880 Cost:  5.021638 
Prediction:
 [[153.90576]
 [182.86018]
 [181.23428]
 [197.84317]
 [138.53926]]
1890 Cost:  4.997808 
Prediction:
 [[153.8978 ]
 [182.86569]
 [181.2319 ]
 [197.84113]
 [138.54677]]
1900 Cost:  4.9740767 
Prediction:
 [[153.88986]
 [182.87119]
 [181.22952]
 [197.83905]
 [138.55426]]
1910 Cost:  4.9505005 
Prediction:
 [[153.88193]
 [182.87663]
 [181.2271 ]
 [197.83699]
 [138.5617 ]]
1920 Cost:  4.9270287 
Prediction:
 [[153.87401]
 [182.8821 ]
 [181.22472]
 [197.83493]
 [138.56914]]
1930 Cost:  4.9036746 
Prediction:
 [[153.86612]
 [182.88754]
 [181.22235]
 [197.83289]
 [138.57657]]
1940 Cost:  4.880481 
Prediction:
 [[153.85826]
 [182.89296]
 [181.22   ]
 [197.83084]
 [138.58397]]
1950 Cost:  4.857375 
Prediction:
 [[153.85043]
 [182.89838]
 [181.21764]
 [197.82881]
 [138.59137]]
1960 Cost:  4.834437 
Prediction:
 [[153.8426 ]
 [182.90376]
 [181.21529]
 [197.82677]


'\n0 Cost:  7105.46\nPrediction:\n [[ 80.82241058]\n [ 92.26364136]\n [ 93.70250702]\n [ 98.09217834]\n [ 72.51759338]]\n10 Cost:  5.89726\nPrediction:\n [[ 155.35159302]\n [ 181.85691833]\n [ 181.97254944]\n [ 194.21760559]\n [ 140.85707092]]\n...\n1990 Cost:  3.18588\nPrediction:\n [[ 154.36352539]\n [ 182.94833374]\n [ 181.85189819]\n [ 194.35585022]\n [ 142.03240967]]\n2000 Cost:  3.1781\nPrediction:\n [[ 154.35881042]\n [ 182.95147705]\n [ 181.85035706]\n [ 194.35533142]\n [ 142.036026  ]]\n'

In [5]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('/home/pirl/Downloads/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

# train output
'''
0 Cost: 21027.0 
Prediction:
 [[22.048063 ]
 [21.619772 ]
 ...
 [31.36112  ]
 [24.986364 ]]
10 Cost: 95.976326 
Prediction:
 [[157.11063 ]
 [183.99283 ]
 ...
 [167.48862 ]
 [193.25117 ]]
 1990 Cost: 24.863274 
Prediction:
 [[154.4393  ]
 [185.5584  ]
 ...
 [158.27443 ]
 [192.79778 ]]
2000 Cost: 24.722485 
Prediction:
 [[154.42894 ]
 [185.5586  ]
 ...
 [158.24257 ]
 [192.79166 ]]
'''

# Ask my score
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[ 181.73277283]]
Other scores will be  [[ 145.86265564]
 [ 187.23129272]]
'''

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)
0 Cost: 21273.258 
Prediction:
 [[ 5.9643626]
 [30.45712  ]
 [17.961147 ]
 [19.166342 ]
 [29.52042  ]
 [24.223494 ]
 [ 7.489695 ]
 [-4.803824 ]
 [33.56457  ]
 [32.53331  ]
 [14.571193 ]
 [24.604677 ]
 [19.29369  ]
 [18.243969 ]
 [10.987984 ]
 [28.41359  ]
 [25.094757 ]
 [ 3.176618 ]
 [14.872594 ]
 [10

250 Cost: 94.99319 
Prediction:
 [[143.48709 ]
 [194.19579 ]
 [180.09102 ]
 [195.7836  ]
 [153.97475 ]
 [115.868034]
 [140.19737 ]
 [ 94.32726 ]
 [186.28615 ]
 [173.95308 ]
 [141.91882 ]
 [149.50536 ]
 [186.72066 ]
 [157.25333 ]
 [144.07909 ]
 [194.75711 ]
 [156.94548 ]
 [162.82748 ]
 [174.72177 ]
 [153.99843 ]
 [167.50443 ]
 [180.55203 ]
 [157.9652  ]
 [146.10405 ]
 [197.93541 ]]
260 Cost: 94.531555 
Prediction:
 [[143.51514]
 [194.16985]
 [180.09602]
 [195.79099]
 [153.93858]
 [115.83733]
 [140.22247]
 [ 94.37498]
 [186.25041]
 [173.91884]
 [141.92326]
 [149.48415]
 [186.72281]
 [157.24832]
 [144.0956 ]
 [194.73814]
 [156.91988]
 [162.87263]
 [174.7327 ]
 [154.01501]
 [167.52461]
 [180.5334 ]
 [157.98894]
 [146.12569]
 [197.91698]]
270 Cost: 94.07237 
Prediction:
 [[143.54308 ]
 [194.144   ]
 [180.10103 ]
 [195.79832 ]
 [153.90251 ]
 [115.80674 ]
 [140.2475  ]
 [ 94.422585]
 [186.21477 ]
 [173.88469 ]
 [141.92769 ]
 [149.463   ]
 [186.72493 ]
 [157.24329 ]
 [144.11206 ]
 [194.71921 ]

660 Cost: 77.95363 
Prediction:
 [[144.5674  ]
 [193.18985 ]
 [180.2807  ]
 [196.07082 ]
 [152.56827 ]
 [114.686806]
 [141.17966 ]
 [ 96.19621 ]
 [184.9104  ]
 [172.65155 ]
 [142.09512 ]
 [148.69345 ]
 [186.79103 ]
 [157.03851 ]
 [144.73065 ]
 [194.02693 ]
 [155.92667 ]
 [164.59201 ]
 [175.13077 ]
 [154.62872 ]
 [168.29663 ]
 [179.83572 ]
 [158.89253 ]
 [146.91852 ]
 [197.21513 ]]
670 Cost: 77.582855 
Prediction:
 [[144.59204 ]
 [193.16672 ]
 [180.28491 ]
 [196.07745 ]
 [152.53584 ]
 [114.6599  ]
 [141.20247 ]
 [ 96.239624]
 [184.87903 ]
 [172.62228 ]
 [142.09927 ]
 [148.67506 ]
 [186.79231 ]
 [157.03308 ]
 [144.74591 ]
 [194.01027 ]
 [155.90262 ]
 [164.63289 ]
 [175.1398  ]
 [154.6429  ]
 [168.31505 ]
 [179.8194  ]
 [158.914   ]
 [146.93661 ]
 [197.19846 ]]
680 Cost: 77.21398 
Prediction:
 [[144.6166 ]
 [193.14363]
 [180.2891 ]
 [196.08405]
 [152.50348]
 [114.63304]
 [141.2252 ]
 [ 96.28292]
 [184.84775]
 [172.59312]
 [142.1034 ]
 [148.65674]
 [186.7936 ]
 [157.02762]
 [144.76114]
 [1

 [196.5938  ]]
1060 Cost: 64.55386 
Prediction:
 [[145.4953  ]
 [192.31287 ]
 [180.4364  ]
 [196.3233  ]
 [151.33588 ]
 [113.673775]
 [142.05157 ]
 [ 97.856186]
 [183.73026 ]
 [171.56403 ]
 [142.25586 ]
 [148.00482 ]
 [186.8298  ]
 [156.8156  ]
 [145.31822 ]
 [193.40082 ]
 [154.99442 ]
 [166.15308 ]
 [175.46123 ]
 [155.15533 ]
 [169.00342 ]
 [179.22244 ]
 [159.71141 ]
 [147.58519 ]
 [196.57866 ]]
1070 Cost: 64.25387 
Prediction:
 [[145.51703 ]
 [192.29218 ]
 [180.43997 ]
 [196.32928 ]
 [151.3067  ]
 [113.650055]
 [142.07236 ]
 [ 97.89575 ]
 [183.70262 ]
 [171.5389  ]
 [142.25974 ]
 [147.9888  ]
 [186.83046 ]
 [156.8099  ]
 [145.3323  ]
 [193.38615 ]
 [154.9719  ]
 [166.1902  ]
 [175.46875 ]
 [155.16751 ]
 [169.0203  ]
 [179.20811 ]
 [159.73087 ]
 [147.6004  ]
 [196.56354 ]]
1080 Cost: 63.95542 
Prediction:
 [[145.53873 ]
 [192.27151 ]
 [180.44351 ]
 [196.33527 ]
 [151.27762 ]
 [113.626396]
 [142.09306 ]
 [ 97.9352  ]
 [183.67505 ]
 [171.51387 ]
 [142.26361 ]
 [147.97281 ]
 [186.83109 ]

1490 Cost: 52.978832 
Prediction:
 [[146.37207 ]
 [191.47208 ]
 [180.57678 ]
 [196.5673  ]
 [150.14853 ]
 [112.718   ]
 [142.90196 ]
 [ 99.476074]
 [182.6166  ]
 [170.56496 ]
 [142.41653 ]
 [147.3623  ]
 [186.84612 ]
 [156.56888 ]
 [145.89963 ]
 [192.81021 ]
 [154.05981 ]
 [167.67085 ]
 [175.75395 ]
 [155.63908 ]
 [169.69608 ]
 [178.64487 ]
 [160.50616 ]
 [148.18423 ]
 [195.96051 ]]
1500 Cost: 52.739452 
Prediction:
 [[146.39111]
 [191.45367]
 [180.57976]
 [196.57266]
 [150.12248]
 [112.69726]
 [142.92072]
 [ 99.51183]
 [182.59242]
 [170.54358]
 [142.4201 ]
 [147.34845]
 [186.84624]
 [156.56311]
 [145.91257]
 [192.7974 ]
 [154.03891]
 [167.70432]
 [175.76009]
 [155.64943]
 [169.71141]
 [178.63232]
 [160.52368]
 [148.19688]
 [195.9469 ]]
1510 Cost: 52.501396 
Prediction:
 [[146.4101 ]
 [191.43533]
 [180.58272]
 [196.57802]
 [150.0965 ]
 [112.67659]
 [142.93945]
 [ 99.54752]
 [182.56834]
 [170.5223 ]
 [142.42369]
 [147.33464]
 [186.84634]
 [156.55733]
 [145.92546]
 [192.78462]
 [154.0180

1920 Cost: 43.737858 
Prediction:
 [[147.1402  ]
 [190.7248  ]
 [180.69383 ]
 [196.78589 ]
 [149.0882  ]
 [111.881966]
 [143.6703  ]
 [100.94046 ]
 [181.64224 ]
 [169.71483 ]
 [142.56499 ]
 [146.80661 ]
 [186.84251 ]
 [156.32097 ]
 [146.4321  ]
 [192.2937  ]
 [153.19379 ]
 [169.03821 ]
 [175.99318 ]
 [156.05069 ]
 [170.32474 ]
 [178.14052 ]
 [161.22096 ]
 [148.68185 ]
 [195.40425 ]]
1930 Cost: 43.54665 
Prediction:
 [[147.15689]
 [190.70844]
 [180.69632]
 [196.79068]
 [149.06493]
 [111.8638 ]
 [143.68726]
 [100.97278]
 [181.62108]
 [169.69664]
 [142.5683 ]
 [146.79463]
 [186.84224]
 [156.31523]
 [146.44392]
 [192.28247]
 [153.17444]
 [169.06833]
 [175.9982 ]
 [156.05948]
 [170.33864]
 [178.12958]
 [161.2367 ]
 [148.69237]
 [195.392  ]]
1940 Cost: 43.356422 
Prediction:
 [[147.17354 ]
 [190.69212 ]
 [180.69879 ]
 [196.79549 ]
 [149.04173 ]
 [111.845695]
 [143.70416 ]
 [101.00501 ]
 [181.59998 ]
 [169.67851 ]
 [142.57161 ]
 [146.78267 ]
 [186.84196 ]
 [156.3095  ]
 [146.45572 ]
 [192.271

'\nYour score will be  [[ 181.73277283]]\nOther scores will be  [[ 145.86265564]\n [ 187.23129272]]\n'

In [6]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['/home/pirl/Downloads/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[185.33531]]
Other scores will be  [[178.36246]
 [177.03687]]
'''

OutOfRangeError: FIFOQueue '_5_batch_1/fifo_queue' is closed and has insufficient elements (requested 9, current size 0)
	 [[node batch_1 (defined at <ipython-input-6-7f8f657fac5b>:20) ]]

Original stack trace for 'batch_1':
  File "/home/pirl/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pirl/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/pirl/anaconda3/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/home/pirl/anaconda3/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/home/pirl/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 781, in inner
    self.run()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-7f8f657fac5b>", line 20, in <module>
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 1021, in batch
    name=name)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 790, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3862, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
