In [2]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('/home/pirl/Downloads/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

# train output
'''
0 Cost: 21027.0 
Prediction:
 [[22.048063 ]
 [21.619772 ]
 ...
 [31.36112  ]
 [24.986364 ]]
10 Cost: 95.976326 
Prediction:
 [[157.11063 ]
 [183.99283 ]
 ...
 [167.48862 ]
 [193.25117 ]]
 1990 Cost: 24.863274 
Prediction:
 [[154.4393  ]
 [185.5584  ]
 ...
 [158.27443 ]
 [192.79778 ]]
2000 Cost: 24.722485 
Prediction:
 [[154.42894 ]
 [185.5586  ]
 ...
 [158.24257 ]
 [192.79166 ]]
'''

# Ask my score
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[ 181.73277283]]
Other scores will be  [[ 145.86265564]
 [ 187.23129272]]
'''

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)
0 Cost: 8013.899 
Prediction:
 [[74.180595]
 [80.63322 ]
 [83.980225]
 [91.3227  ]
 [59.210712]
 [41.890907]
 [70.11859 ]
 [54.823997]
 [72.922676]
 [66.100105]
 [65.148254]
 [60.243664]
 [86.905014]
 [71.78623 ]
 [69.10599 ]
 [82.41498 ]
 [65.882515]
 [86.28957 ]
 [84.18406 ]
 [76.09278 ]
 [81.279625

210 Cost: 22.83243 
Prediction:
 [[157.78003 ]
 [181.85788 ]
 [183.32124 ]
 [199.67047 ]
 [136.46611 ]
 [ 99.178764]
 [151.24602 ]
 [114.98031 ]
 [167.89015 ]
 [154.4786  ]
 [143.37059 ]
 [137.76215 ]
 [189.38982 ]
 [156.80588 ]
 [150.73518 ]
 [185.21565 ]
 [146.89247 ]
 [183.5772  ]
 [181.74872 ]
 [163.33777 ]
 [176.46535 ]
 [170.94978 ]
 [168.89339 ]
 [159.0328  ]
 [189.82619 ]]
220 Cost: 22.69007 
Prediction:
 [[157.76027]
 [181.86807]
 [183.3132 ]
 [199.66884]
 [136.47643]
 [ 99.20134]
 [151.2459 ]
 [114.98073]
 [167.91626]
 [154.5216 ]
 [143.37326]
 [137.78249]
 [189.3748 ]
 [156.78549]
 [150.74092]
 [185.22966]
 [146.87492]
 [183.57368]
 [181.72804]
 [163.3169 ]
 [176.46754]
 [170.96413]
 [168.89055]
 [158.9971 ]
 [189.82806]]
230 Cost: 22.548952 
Prediction:
 [[157.74062 ]
 [181.87825 ]
 [183.30525 ]
 [199.66728 ]
 [136.48674 ]
 [ 99.223854]
 [151.24579 ]
 [114.98116 ]
 [167.9423  ]
 [154.56445 ]
 [143.37595 ]
 [137.80278 ]
 [189.35991 ]
 [156.76524 ]
 [150.74666 ]
 [185.24364 ]

510 Cost: 19.052952 
Prediction:
 [[157.2219  ]
 [182.14787 ]
 [183.09544 ]
 [199.62471 ]
 [136.76088 ]
 [ 99.81701 ]
 [151.23962 ]
 [114.986176]
 [168.62848 ]
 [155.69069 ]
 [143.44534 ]
 [138.3365  ]
 [188.96889 ]
 [156.2348  ]
 [150.89442 ]
 [185.61177 ]
 [146.40392 ]
 [183.47322 ]
 [181.16766 ]
 [162.75014 ]
 [176.52464 ]
 [171.35551 ]
 [168.81145 ]
 [158.02808 ]
 [189.88185 ]]
520 Cost: 18.943052 
Prediction:
 [[157.20447]
 [182.15698]
 [183.08842]
 [199.62325]
 [136.77019]
 [ 99.83692]
 [151.23932]
 [114.98612]
 [168.65154]
 [155.72841]
 [143.44765]
 [138.35442]
 [188.95584]
 [156.21713]
 [150.89928]
 [185.62413]
 [146.38889]
 [183.4698 ]
 [181.14961]
 [162.73186]
 [176.52638]
 [171.36816]
 [168.80879]
 [157.99684]
 [189.88365]]
530 Cost: 18.834045 
Prediction:
 [[157.18712]
 [182.16606]
 [183.08145]
 [199.62181]
 [136.77946]
 [ 99.85677]
 [151.239  ]
 [114.98607]
 [168.67451]
 [155.76598]
 [143.44994]
 [138.37224]
 [188.94286]
 [156.19954]
 [150.90413]
 [185.63646]
 [146.37395]


 [189.9228 ]]
750 Cost: 16.658634 
Prediction:
 [[156.82294]
 [182.35725]
 [182.93523]
 [199.59106]
 [136.97551]
 [100.27296]
 [151.2305 ]
 [114.98148]
 [169.156  ]
 [156.55215]
 [143.49725]
 [138.74564]
 [188.67154]
 [155.83282]
 [151.00372]
 [185.89474]
 [146.06395]
 [183.39154]
 [180.7557 ]
 [162.33249]
 [176.56276]
 [171.64519]
 [168.74925]
 [157.31523]
 [189.92453]]
760 Cost: 16.569155 
Prediction:
 [[156.80716 ]
 [182.36557 ]
 [182.92891 ]
 [199.58972 ]
 [136.98407 ]
 [100.29099 ]
 [151.23004 ]
 [114.981125]
 [169.17686 ]
 [156.58612 ]
 [143.49928 ]
 [138.76181 ]
 [188.65985 ]
 [155.81705 ]
 [151.00795 ]
 [185.90594 ]
 [146.05069 ]
 [183.38817 ]
 [180.73947 ]
 [162.31602 ]
 [176.56418 ]
 [171.65665 ]
 [168.74673 ]
 [157.28714 ]
 [189.92628 ]]
770 Cost: 16.480474 
Prediction:
 [[156.79146]
 [182.37387]
 [182.92264]
 [199.58838]
 [136.99261]
 [100.30893]
 [151.22958]
 [114.98076]
 [169.19763]
 [156.61995]
 [143.5013 ]
 [138.77788]
 [188.64822]
 [155.80135]
 [151.01216]
 [185.91708]

1020 Cost: 14.493012 
Prediction:
 [[156.41913]
 [182.57129]
 [182.77422]
 [199.55614]
 [137.19666]
 [100.7342 ]
 [151.21674]
 [114.96797]
 [169.68973]
 [157.41928]
 [143.54834]
 [139.1584 ]
 [188.37405]
 [155.4321 ]
 [151.1099 ]
 [186.18105]
 [145.72899]
 [183.3016 ]
 [180.34207]
 [161.91214]
 [176.59712]
 [171.93811]
 [168.68275]
 [156.59897]
 [189.97063]]
1030 Cost: 14.422015 
Prediction:
 [[156.40503]
 [182.5788 ]
 [182.7686 ]
 [199.55489]
 [137.20447]
 [100.75031]
 [151.21617]
 [114.96732]
 [169.70836]
 [157.44946]
 [143.55008]
 [139.17278]
 [188.36372]
 [155.41823]
 [151.11351]
 [186.19104]
 [145.71745]
 [183.29831]
 [180.32768]
 [161.89748]
 [176.59824]
 [171.94833]
 [168.68034]
 [156.57404]
 [189.97227]]
1040 Cost: 14.351609 
Prediction:
 [[156.39098]
 [182.58629]
 [182.76302]
 [199.55365]
 [137.21223]
 [100.76635]
 [151.21559]
 [114.96666]
 [169.72691]
 [157.47954]
 [143.55182]
 [139.1871 ]
 [188.35344]
 [155.4044 ]
 [151.11711]
 [186.20099]
 [145.70601]
 [183.29503]
 [180.313

1330 Cost: 12.550835 
Prediction:
 [[156.00783]
 [182.79176]
 [182.61159]
 [199.51942]
 [137.42656]
 [101.2037 ]
 [151.19731]
 [114.94371]
 [170.23305]
 [158.29666]
 [143.59853]
 [139.5771 ]
 [188.07518]
 [155.0313 ]
 [151.21268]
 [186.47243]
 [145.39874]
 [183.20126]
 [179.92476]
 [161.48677]
 [176.62706]
 [172.23607]
 [168.6107 ]
 [155.87569]
 [190.02098]]
1340 Cost: 12.496312 
Prediction:
 [[155.9954 ]
 [182.79845]
 [182.6067 ]
 [199.5183 ]
 [137.43358]
 [101.21785]
 [151.19661]
 [114.94279]
 [170.24942]
 [158.32304]
 [143.60002]
 [139.5897 ]
 [188.06624]
 [155.01932]
 [151.21568]
 [186.48122]
 [145.38898]
 [183.19807]
 [179.91222]
 [161.47398]
 [176.62788]
 [172.24506]
 [168.60846]
 [155.85396]
 [190.02254]]
1350 Cost: 12.442262 
Prediction:
 [[155.98305]
 [182.80513]
 [182.60184]
 [199.51717]
 [137.44057]
 [101.23196]
 [151.19594]
 [114.94186]
 [170.26576]
 [158.34929]
 [143.6015 ]
 [139.60226]
 [188.05733]
 [155.0074 ]
 [151.21867]
 [186.48997]
 [145.37926]
 [183.1949 ]
 [179.899

 [190.06865]]
1650 Cost: 11.016781 
Prediction:
 [[155.63487]
 [182.9942 ]
 [182.46555]
 [199.48502]
 [137.63979]
 [101.62904]
 [151.1741 ]
 [114.91091]
 [170.72534]
 [159.08618]
 [143.64221]
 [139.95502]
 [187.80846]
 [154.67542]
 [151.30035]
 [186.73643]
 [145.11058]
 [183.10133]
 [179.55048]
 [161.104  ]
 [176.64902]
 [172.50583]
 [168.54099]
 [155.22635]
 [190.07013]]
1660 Cost: 10.975234 
Prediction:
 [[155.624  ]
 [183.00017]
 [182.46132]
 [199.48401]
 [137.64609]
 [101.64145]
 [151.17336]
 [114.90979]
 [170.73972]
 [159.10913]
 [143.64346]
 [139.96602]
 [187.80075]
 [154.66516]
 [151.30283]
 [186.74414]
 [145.10236]
 [183.09827]
 [179.53961]
 [161.0929 ]
 [176.64957]
 [172.5137 ]
 [168.53888]
 [155.20752]
 [190.07162]]
1670 Cost: 10.934042 
Prediction:
 [[155.61316]
 [183.0061 ]
 [182.4571 ]
 [199.483  ]
 [137.65237]
 [101.6538 ]
 [151.1726 ]
 [114.90865]
 [170.75403]
 [159.13197]
 [143.64471]
 [139.97699]
 [187.79309]
 [154.65497]
 [151.30528]
 [186.75182]
 [145.09418]
 [183.09

1890 Cost: 10.110181 
Prediction:
 [[155.3856 ]
 [183.13112]
 [182.36884]
 [199.46132]
 [137.78526]
 [101.91313]
 [151.15517]
 [114.88231]
 [171.05423]
 [159.61018]
 [143.67027]
 [140.20654]
 [187.63286]
 [154.44228]
 [151.35555]
 [186.91277]
 [144.92494]
 [183.029  ]
 [179.30284]
 [160.84999]
 [176.66048]
 [172.6859 ]
 [168.49165]
 [154.79637]
 [190.10518]]
1900 Cost: 10.076247 
Prediction:
 [[155.37575]
 [183.13658]
 [182.36504]
 [199.46037]
 [137.79109]
 [101.92437]
 [151.15437]
 [114.88105]
 [171.06725]
 [159.63084]
 [143.67136]
 [140.21648]
 [187.62595]
 [154.43312]
 [151.35767]
 [186.91974]
 [144.91772]
 [183.02605]
 [179.2931 ]
 [160.83997]
 [176.66087]
 [172.69302]
 [168.48964]
 [154.77943]
 [190.10661]]
1910 Cost: 10.042584 
Prediction:
 [[155.3659 ]
 [183.142  ]
 [182.36124]
 [199.45943]
 [137.79688]
 [101.93557]
 [151.15356]
 [114.8798 ]
 [171.0802 ]
 [159.65143]
 [143.67244]
 [140.22638]
 [187.61908]
 [154.42404]
 [151.35979]
 [186.9267 ]
 [144.91055]
 [183.02309]
 [179.283

'\nYour score will be  [[ 181.73277283]]\nOther scores will be  [[ 145.86265564]\n [ 187.23129272]]\n'

In [3]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['/home/pirl/Downloads/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[185.33531]]
Other scores will be  [[178.36246]
 [177.03687]]
'''

W0715 23:46:50.121131 139976227407616 deprecation.py:323] From <ipython-input-3-7f8f657fac5b>:8: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0715 23:46:50.183722 139976227407616 deprecation.py:323] From /home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...

0 Cost:  26240.918 
Prediction:
 [[-7.884923  ]
 [-2.5348966 ]
 [-6.153245  ]
 [-6.321269  ]
 [-0.41728717]
 [ 1.2950747 ]
 [-5.956776  ]
 [-6.3819056 ]
 [-0.18749315]
 [ 1.4264901 ]]
10 Cost:  14.79098 
Prediction:
 [[149.79247 ]
 [186.99254 ]
 [180.58345 ]
 [197.05733 ]
 [144.12495 ]
 [107.8744  ]
 [146.28752 ]
 [106.493935]
 [176.95256 ]
 [165.52055 ]]
20 Cost:  16.757053 
Prediction:
 [[150.86334 ]
 [188.26315 ]
 [181.84375 ]
 [198.43185 ]
 [145.08829 ]
 [108.585724]
 [147.32394 ]
 [107.273346]
 [178.13863 ]
 [166.62202 ]]
30 Cost:  16.71402 
Prediction:
 [[150.8774  ]
 [188.26338 ]
 [181.8524  ]
 [198.4432  ]
 [145.08275 ]
 [108.582664]
 [147.33998 ]
 [107.29626 ]
 [178.13734 ]
 [166.6236  ]]
40 Cost:  16.649601 
Prediction:
 [[150.88428]
 [188.25507]
 [181.8526 ]
 [198.44534]
 [145.07068]
 [108.5748 ]
 [147.34909]
 [107.31401]
 [178.12805]
 [166.61775]]
50 Cost:  16.5854 
Prediction:
 [[150.89111 ]
 [188.24672 ]
 [181.85275 ]
 [198.44742 ]
 [145.05861 ]
 [108.566925]
 [147.35815 

490 Cost:  14.068212 
Prediction:
 [[151.17387 ]
 [187.89995 ]
 [181.85834 ]
 [198.53392 ]
 [144.55702 ]
 [108.240944]
 [147.73524 ]
 [108.06826 ]
 [177.73367 ]
 [166.37161 ]]
500 Cost:  14.017496 
Prediction:
 [[151.17992]
 [187.89253]
 [181.85846]
 [198.5358 ]
 [144.54626]
 [108.23398]
 [147.74338]
 [108.0841 ]
 [177.72546]
 [166.36658]]
510 Cost:  13.966978 
Prediction:
 [[151.18593 ]
 [187.8851  ]
 [181.85855 ]
 [198.53764 ]
 [144.53554 ]
 [108.227036]
 [147.75145 ]
 [108.09989 ]
 [177.71724 ]
 [166.3615  ]]
520 Cost:  13.916768 
Prediction:
 [[151.19196]
 [187.87772]
 [181.85867]
 [198.53949]
 [144.52484]
 [108.22011]
 [147.75952]
 [108.11565]
 [177.70908]
 [166.35645]]
530 Cost:  13.866827 
Prediction:
 [[151.19794]
 [187.87035]
 [181.85878]
 [198.54134]
 [144.51416]
 [108.21322]
 [147.76756]
 [108.13137]
 [177.70091]
 [166.35143]]
540 Cost:  13.817143 
Prediction:
 [[151.20392]
 [187.863  ]
 [181.85887]
 [198.5432 ]
 [144.50351]
 [108.20632]
 [147.77562]
 [108.14704]
 [177.6928 

1050 Cost:  11.59857 
Prediction:
 [[151.48822 ]
 [187.51216 ]
 [181.8633  ]
 [198.6314  ]
 [143.99486 ]
 [107.878975]
 [148.16003 ]
 [108.8977  ]
 [177.30614 ]
 [166.1107  ]]
1060 Cost:  11.560696 
Prediction:
 [[151.49341]
 [187.50572]
 [181.86334]
 [198.633  ]
 [143.98552]
 [107.873  ]
 [148.16708]
 [108.91149]
 [177.29907]
 [166.10645]]
1070 Cost:  11.523043 
Prediction:
 [[151.4986 ]
 [187.49931]
 [181.86342]
 [198.6346 ]
 [143.97621]
 [107.86705]
 [148.17415]
 [108.92526]
 [177.29204]
 [166.10222]]
1080 Cost:  11.48556 
Prediction:
 [[151.50375 ]
 [187.49292 ]
 [181.86348 ]
 [198.63622 ]
 [143.96692 ]
 [107.8611  ]
 [148.18118 ]
 [108.938995]
 [177.285   ]
 [166.09799 ]]
1090 Cost:  11.448321 
Prediction:
 [[151.5089 ]
 [187.48654]
 [181.86354]
 [198.63783]
 [143.95767]
 [107.85519]
 [148.18819]
 [108.95269]
 [177.278  ]
 [166.09377]]
1100 Cost:  11.411238 
Prediction:
 [[151.51404 ]
 [187.48016 ]
 [181.86362 ]
 [198.63943 ]
 [143.94844 ]
 [107.849266]
 [148.19519 ]
 [108.966354]

1580 Cost:  9.842377 
Prediction:
 [[151.7451  ]
 [187.19339 ]
 [181.86627 ]
 [198.71207 ]
 [143.53171 ]
 [107.58356 ]
 [148.51169 ]
 [109.584175]
 [176.95723 ]
 [165.90259 ]]
1590 Cost:  9.8136835 
Prediction:
 [[151.74959 ]
 [187.18777 ]
 [181.8663  ]
 [198.71349 ]
 [143.52354 ]
 [107.578384]
 [148.51788 ]
 [109.5963  ]
 [176.95111 ]
 [165.89897 ]]
1600 Cost:  9.785174 
Prediction:
 [[151.75409]
 [187.18217]
 [181.86635]
 [198.7149 ]
 [143.51541]
 [107.57322]
 [148.52408]
 [109.60837]
 [176.945  ]
 [165.89539]]
1610 Cost:  9.756815 
Prediction:
 [[151.75858]
 [187.1766 ]
 [181.8664 ]
 [198.71632]
 [143.50731]
 [107.56807]
 [148.53024]
 [109.62042]
 [176.93893]
 [165.8918 ]]
1620 Cost:  9.728618 
Prediction:
 [[151.76303 ]
 [187.17105 ]
 [181.86644 ]
 [198.71774 ]
 [143.49922 ]
 [107.56294 ]
 [148.5364  ]
 [109.632454]
 [176.93288 ]
 [165.88824 ]]
1630 Cost:  9.700499 
Prediction:
 [[151.76749 ]
 [187.16548 ]
 [181.86647 ]
 [198.71913 ]
 [143.49113 ]
 [107.557816]
 [148.54256 ]
 [109.

'\nYour score will be  [[185.33531]]\nOther scores will be  [[178.36246]\n [177.03687]]\n'